### PR TITLE
Index - Remove applicant info

### PR DESCRIPTION
**Pull request by jomey**
Also minor fix to match the top right navigation with the sequence of the main body.

### CODE REVIEW

**Comment by jomey** [comment]
Should we also move the "About" section below the team again (as we did with ICESat-2)?
Now that the event is getting closer, I feel that the schedule will be most relevant again.

**Review by scottyhq — APPROVED** [review]
> Should we also move the "About" section below the team again (as we did with ICESat-2)?
Now that the event is getting closer, I feel that the schedule will be most relevant again. 

I agree it's nice for the user interface, but not essential. up to you!

**Comment by aaarendt** [comment]
@jomey thanks for making these changes!

@markweldensmith  suggested we add the location of the tutorials on the main website. Quickest way is this change to index.html:


`Tutorials will be located in <a href= "https://hfs.uw.edu/Meeting-Spaces/Alder-Auditorium" target="_blank">
                Alder Auditorium.</a>`

OK for now or should we generalize this by making cookie cutter variables?

**Comment by jomey** [comment]
> @markweldensmith suggested we add the location of the tutorials on the main website. Quickest way is this change to index.html:
> 
> `Tutorials will be located in <a href= "https://hfs.uw.edu/Meeting-Spaces/Alder-Auditorium" target="_blank"> Alder Auditorium.</a>`
> 
> OK for now or should we generalize this by making cookie cutter variables?

Should this go above the schedule for instance? Or as a button along with the link to the ‘Jupyter Book’?

Both are fairly straight forward to add.

**Comment by aaarendt** [comment]
@jomey see my suggested location

**Pull request merged**
